# Numpy Arrays

In [1]:
import numpy as np


In [2]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [3]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [4]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Numpy Randoms

In [7]:
np.random.rand(4)

array([0.84845413, 0.05178108, 0.8382247 , 0.07475379])

In [8]:
np.random.rand(5, 5)

array([[0.34541541, 0.66933709, 0.61741562, 0.72295741, 0.3120689 ],
       [0.4220066 , 0.39434741, 0.37085579, 0.38309085, 0.77345954],
       [0.11371971, 0.70437958, 0.33450328, 0.43693666, 0.35172261],
       [0.37714107, 0.12225392, 0.55757995, 0.1420005 , 0.54710572],
       [0.15776915, 0.34713728, 0.05007561, 0.94779624, 0.14678798]])

In [2]:
np.random.randn(10)

array([-0.4044336 , -0.86565089,  0.56094607,  0.00758893,  0.51257307,
       -0.22249991, -1.37753653, -0.8613037 , -1.62383685, -0.91667992])

In [3]:
np.random.normal(3,4,10)

array([ 3.78937715, -1.74392471,  4.96428283,  0.80495933,  0.12458279,
       -0.59435629,  0.64146372,  7.53629534, -3.03715482,  8.33822391])

In [5]:
np.random.randint(1,  199, 10)

array([132, 181,  57, 167, 160,  23, 146, 142, 125, 190])

In [7]:
np.random.seed(42)


In [8]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# Properties

In [9]:
ar = np.random.randint(0,  50, 10)

In [15]:
ar.reshape(2,-1)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]])

In [16]:
ar

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [17]:
ar.max()

39

In [18]:
ar.min()

2

In [19]:
ar.argmax()

7

In [20]:
ar.argmin()


9

In [21]:
ar.dtype

dtype('int64')

# Indexing and Selection

In [22]:
arr = np.arange(0,11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[8]

8

In [25]:
arr[1:5]

array([1, 2, 3, 4])

# Broadcasting

In [26]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [27]:
arr / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [28]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# References

In [31]:
slice_ = arr[0:6]

In [32]:
slice_[:] = 99

In [33]:
slice_

array([99, 99, 99, 99, 99, 99])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr_copy = arr.copy()

In [36]:
arr_copy[:] = 3

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
arr_copy

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [39]:
arr_2d = np.random.randn(3,3) *20

In [40]:
arr_2d

array([[ -9.38948772,  10.85120087,  -9.26835386],
       [ -9.31459507,   4.83924543, -38.26560489],
       [-34.49835665, -11.24575058, -20.25662241]])

In [41]:
arr_2d.shape

(3, 3)

In [43]:
arr_2d[1,:]

array([ -9.31459507,   4.83924543, -38.26560489])

In [44]:
arr_2d[2,2]

-20.256622406688475

In [45]:
arr_2d[0:2,1:]

array([[ 10.85120087,  -9.26835386],
       [  4.83924543, -38.26560489]])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr[(arr>3) & (arr<10)]

array([6, 7, 8, 9])

In [49]:
arr /100

array([0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [50]:
arr **2

array([9801, 9801, 9801, 9801, 9801, 9801,   36,   49,   64,   81,  100])

In [51]:
arr/0

/home/javemar/miniconda2/envs/spark-portilla/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [52]:
arr_2d

array([[ -9.38948772,  10.85120087,  -9.26835386],
       [ -9.31459507,   4.83924543, -38.26560489],
       [-34.49835665, -11.24575058, -20.25662241]])

In [53]:
arr_2d.sum(axis=1)

array([ -7.8066407 , -42.74095453, -66.00072964])

In [54]:
arr_2d.sum(axis=0)

array([-53.20243944,   4.44469572, -67.79058116])